Task - 1:
Create a Python program that converts between different units of measurement.
• The program should:
1. Prompt the user to choose the type of conversion (e.g., length, weight, volume).
2. Ask the user to input the value to be converted.
3. Perform the conversion and display the result.
4. Handle potential errors, such as invalid input or unsupported conversion types.
• Requirements:
1. Functions: Define at least one function to perform the conversion.
2. Error Handling: Use try-except blocks to handle invalid input (e.g., non-numeric values).
3. User Input: Prompt the user to select the conversion type and input the value.
4. Docstrings: Include a docstring in your function to describe its purpose, parameters, and
return value.
• Conversion Options:
1. Length:
– Convert meters (m) to feet (ft).
– Convert feet (ft) to meters (m).
2. Weight:
– Convert kilograms (kg) to pounds (lbs).
– Convert pounds (lbs) to kilograms (kg).
3. Volume:
– Convert liters (L) to gallons (gal).
– Convert gallons (gal) to liters (L).


In [5]:
def convert_units():
    print("Choose a conversion type:")
    print("1. Meters to Feet")
    print("2. Feet to Meters")
    print("3. Kilograms to Pounds")
    print("4. Pounds to Kilograms")
    print("5. Liters to Gallons")
    print("6. Gallons to Liters")

    try:
        choice = int(input("Enter your choice (1-6): "))
        value = float(input("Enter the value to convert: "))

        if choice == 1:
            result = value * 3.28084
            print(f"{value} meters is {result:.2f} feet.")
        elif choice == 2:
            result = value / 3.28084
            print(f"{value} feet is {result:.2f} meters.")
        elif choice == 3:
            result = value * 2.20462
            print(f"{value} kilograms is {result:.2f} pounds.")
        elif choice == 4:
            result = value / 2.20462
            print(f"{value} pounds is {result:.2f} kilograms.")
        elif choice == 5:
            result = value * 0.264172
            print(f"{value} liters is {result:.2f} gallons.")
        elif choice == 6:
            result = value / 0.264172
            print(f"{value} gallons is {result:.2f} liters.")
        else:
            print("Invalid choice. Please select a number from 1 to 6.")
    except ValueError:
        print("Invalid input. Please enter a numeric value.")


convert_units()


Choose a conversion type:
1. Meters to Feet
2. Feet to Meters
3. Kilograms to Pounds
4. Pounds to Kilograms
5. Liters to Gallons
6. Gallons to Liters
Enter your choice (1-6): 2
Enter the value to convert: 4
4.0 feet is 1.22 meters.


Task - 2:
Create a Python program that performs various mathematical operations on a list of numbers.
• The Program should:
1. Prompt the user to choose an operation (e.g., find the sum, average, maximum, or minimum
of the numbers).
2. Ask the user to input a list of numbers (separated by spaces).

3. Perform the selected operation and display the result.
4. Handle potential errors, such as invalid input or empty lists.

• Requirements:
1. Functions: Define at least one function for each operation (sum, average, maximum, minimum).
2. Error Handling: Use try-except blocks to handle invalid input (e.g., non-numeric values or
empty lists).
3. User Input: Prompt the user to select the operation and input the list of numbers.
4. Docstrings: Include a docstring in each function to describe its purpose, parameters, and
return value

In [6]:
def find_sum(numbers: list[float]) -> float:

    return sum(numbers)

def find_average(numbers: list[float]) -> float:

    return sum(numbers) / len(numbers) if numbers else 0

def find_maximum(numbers: list[float]) -> float:

    return max(numbers)

def find_minimum(numbers: list[float]) -> float:

    return min(numbers)

def main():

    try:
        print("Choose an operation:")
        print("1. Find Sum")
        print("2. Find Average")
        print("3. Find Maximum")
        print("4. Find Minimum")

        choice = int(input("Enter your choice (1-4): "))
        numbers = list(map(float, input("Enter a list of numbers separated by spaces: ").split()))

        if not numbers:
            print("Error: The list cannot be empty.")
            return

        if choice == 1:
            print(f"Sum: {find_sum(numbers)}")
        elif choice == 2:
            print(f"Average: {find_average(numbers)}")
        elif choice == 3:
            print(f"Maximum: {find_maximum(numbers)}")
        elif choice == 4:
            print(f"Minimum: {find_minimum(numbers)}")
        else:
            print("Invalid choice. Please select a valid option.")
    except ValueError:
        print("Invalid input. Please enter numeric values only.")


main()


Choose an operation:
1. Find Sum
2. Find Average
3. Find Maximum
4. Find Minimum
Enter your choice (1-4): 3
Enter a list of numbers separated by spaces:  4 6 7
Maximum: 7.0


4.2 Exercise on List Manipulation:
1. Extract Every Other Element:
Write a Python function that extracts every other element from a list, starting from the first element.

• Requirements:
– Define a function extract every other(lst) that takes a list lst as input and returns a
new list containing every other element from the original list.
– Example: For the input [1, 2, 3, 4, 5, 6], the output should be [1, 3, 5].

In [7]:
def extract_every_other(lst: list) -> list:
    return lst[::2]

def main():

    try:
        numbers = list(map(int, input("Enter a list of numbers separated by spaces: ").split()))
        if not numbers:
            print("Error: The list cannot be empty.")
            return
        print(f"Every Other Element: {extract_every_other(numbers)}")
    except ValueError:
        print("Invalid input. Please enter numeric values only.")


main()


Enter a list of numbers separated by spaces: 4 7 8 1 2 3
Every Other Element: [4, 8, 2]


2. Slice a Sublist:

Write a Python function that returns a sublist from a given list, starting from a specified index and
ending at another specified index.

• Requirements:

–Define a function get sublist(lst, start, end) that takes a list lst, a starting index
start, and an ending index end as input and returns the sublist from start to end (inclusive).

– Example: For the input [1, 2, 3, 4, 5, 6] with start=2 and end=4, the output should
be [3, 4, 5].


In [8]:
def extract_every_other(lst: list) -> list:

    return lst[::2]

def get_sublist(lst: list, start: int, end: int) -> list:

    return lst[start:end+1]

def main():

    try:
        numbers = list(map(int, input("Enter a list of numbers separated by spaces: ").split()))
        if not numbers:
            print("Error: The list cannot be empty.")
            return

        print(f"Every Other Element: {extract_every_other(numbers)}")

        start = int(input("Enter start index for sublist: "))
        end = int(input("Enter end index for sublist: "))
        print(f"Sublist: {get_sublist(numbers, start, end)}")
    except ValueError:
        print("Invalid input. Please enter numeric values only.")

main()


Enter a list of numbers separated by spaces: 1 2 3 4 5 6
Every Other Element: [1, 3, 5]
Enter start index for sublist: 2
Enter end index for sublist: 3
Sublist: [3, 4]


3.Reverse a List Using Slicing:

Write a Python function that reverses a list using slicing.

• Requirements:

– Define a function reverse list(lst) that takes a list lst and returns a reversed list using
slicing.
– Example: For the input [1, 2, 3, 4, 5], the output should be [5, 4, 3, 2, 1].


In [ ]:
def reverse_list(lst: list) -> list:

    return lst[::-1]

def main():

    try:
        numbers = list(map(int, input("Enter a list of numbers separated by spaces: ").split()))
        if not numbers:
            print("Error: The list cannot be empty.")
            return

        print(f"Reversed List: {reverse_list(numbers)}")
    except ValueError:
        print("Invalid input. Please enter numeric values only.")


main()


Enter a list of numbers separated by spaces: 5
Reversed List: [5]


4.Remove the First and Last Elements:

Write a Python function that removes the first and last elements of a list and returns the resulting
sublist.

• Requirements:

– Define a function remove first last(lst) that takes a list lst and returns a sublist without
the first and last elements using slicing.
– Example: For the input [1, 2, 3, 4, 5], the output should be [2, 3, 4].

In [ ]:
def remove_first_last(lst: list) -> list:

    return lst[1:-1] if len(lst) > 2 else []

def main():

    try:
        numbers = list(map(int, input("Enter a list of numbers separated by spaces: ").split()))
        if not numbers:
            print("Error: The list cannot be empty.")
            return

        print(f"List without first and last elements: {remove_first_last(numbers)}")
    except ValueError:
        print("Invalid input. Please enter numeric values only.")


main()


Enter a list of numbers separated by spaces: 6 7 8 3
List without first and last elements: [7, 8]


5.Get the First n Elements:
Write a Python function that extracts the first n elements from a list.

• Requirements:

– Define a function get first n(lst, n) that takes a list lst and an integer n as input and
returns the first n elements of the list using slicing.

– Example: For the input [1, 2, 3, 4, 5] with n=3, the output should be [1, 2, 3].

In [ ]:
def get_first_n(lst: list, n: int) -> list:

    return lst[:n] if n > 0 else []

def main():

    try:
        numbers = list(map(int, input("Enter a list of numbers separated by spaces: ").split()))
        if not numbers:
            print("Error: The list cannot be empty.")
            return

        n = int(input("Enter the number of first elements to extract: "))
        print(f"First {n} elements: {get_first_n(numbers, n)}")
    except ValueError:
        print("Invalid input. Please enter numeric values only.")


main()

Enter a list of numbers separated by spaces: 4 7 9 2 3
Enter the number of first elements to extract: 3
First 3 elements: [4, 7, 9]


6.Extract Elements from the End:
Write a Python function that extracts the last n elements of a list using slicing.

• Requirements:

– Define a function get last n(lst, n) that takes a list lst and an integer n as input and
returns the last n elements of the list.
– Example: For the input [1, 2, 3, 4, 5] with n=2, the output should be [4, 5].

In [ ]:
def get_last_n(lst: list, n: int) -> list:
    return lst[-n:] if n > 0 else []

def main():
    try:
        numbers = list(map(int, input("Enter a list of numbers separated by spaces: ").split()))
        if not numbers:
            print("Error: The list cannot be empty.")
            return

        n = int(input("Enter the number of last elements to extract: "))
        print(f"Last {n} elements: {get_last_n(numbers, n)}")
    except ValueError:
        print("Invalid input. Please enter numeric values only.")


main()


Enter a list of numbers separated by spaces: 4 5 6 3 5 3
Enter the number of last elements to extract: 3
Last 3 elements: [3, 5, 3]


7.Extract Elements in Reverse Order:

Write a Python function that extracts a list of elements in reverse order starting from the second-to-last
element and skipping one element in between.

• Requirements:

– Define a function reverse skip(lst) that takes a list lst and returns a new list containing
every second element starting from the second-to-last, moving backward.

– Example: For the input [1, 2, 3, 4, 5, 6], the output should be [5, 3, 1].


In [ ]:
def reverse_skip(lst: list) -> list:
    return lst[-2::-2]

def main():
    try:
        numbers = list(map(int, input("Enter a list of numbers separated by spaces: ").split()))
        if not numbers:
            print("Error: The list cannot be empty.")
            return

        print(f"Elements in reverse order (skipping one): {reverse_skip(numbers)}")
    except ValueError:
        print("Invalid input. Please enter numeric values only.")


main()


Enter a list of numbers separated by spaces: 2 4 7 4 5 3 7 3 7
Elements in reverse order (skipping one): [3, 3, 4, 4]


1.Flatten a Nested List:
Write a Python function that takes a nested list and flattens it into a single list, where all the elements
are in a single dimension.

• Requirements:

– Define a function flatten(lst) that takes a nested list lst and returns a flattened version
of the list.
– Example: For the input [[1, 2], [3, 4], [5]], the output should be [1, 2, 3, 4, 5].


In [ ]:
def flatten(lst: list) -> list:
    return [item for sublist in lst for item in sublist]

def main():

    try:
        nested_list = eval(input("Enter a nested list (e.g., [[1,2],[3,4],[5]]): "))
        if not isinstance(nested_list, list) or not all(isinstance(sub, list) for sub in nested_list):
            print("Error: Please enter a valid nested list.")
            return

        print(f"Flattened List: {flatten(nested_list)}")
    except Exception as e:
        print(f"Invalid input: {e}")


main()


Enter a nested list (e.g., [[1,2],[3,4],[5]]): [[1,2],[3,4],[5]]
Flattened List: [1, 2, 3, 4, 5]


2.Accessing Nested List Elements:

 Write a Python function that extracts a specific element from a nested list given its indices.


 • Requirements:

 – Define a function access nested
 element(lst, indices) that takes a nested list lst and
 a list of indices indices, and returns the element at that position.– Example: For the input lst = [[1, 2, 3], [4, 5, 6], [7, 8, 9]] with indices = [1,
 2], the output should be 6.

In [4]:
def access_nested_element(lst: list, indices: list) -> int:
    try:
        element = lst
        for index in indices:
            element = element[index]
        return element
    except (IndexError, TypeError):
        return "Error: Invalid indices or structure."

def main():
    try:
        nested_list = eval(input("Enter a nested list (e.g., [[1,2,3],[4,5,6],[7,8,9]]): "))
        indices = list(map(int, input("Enter indices separated by spaces (e.g., 1 2): ").split()))

        print(f"Accessed Element: {access_nested_element(nested_list, indices)}")
    except Exception as e:
        print(f"Invalid input: {e}")


main()


Enter a nested list (e.g., [[1,2,3],[4,5,6],[7,8,9]]): [[1,2,3],[4,5,6],[7,8,9]]
Enter indices separated by spaces (e.g., 1 2): 1 2
Accessed Element: 6


 3. Sum of All Elements in a Nested List:

 Write a Python function that calculates the sum of all the numbers in a nested list (regardless of depth).

 • Requirements:

 – Define a function sum
 nested(lst) that takes a nested list lst and returns the sum of all
 the elements.

 – Example: For the input [[1, 2], [3, [4, 5]], 6], the output should be 21.

In [ ]:
def sum_nested(lst: list) -> int:
    total = 0
    for item in lst:
        if isinstance(item, list):
            total += sum_nested(item)  # Recursively sum nested lists
        else:
            total += item  # Add number to total
    return total

def main():
    try:
        nested_list = eval(input("Enter a nested list (e.g., [[1,2],[3,[4,5]],6]): "))
        print(f"Sum of all elements: {sum_nested(nested_list)}")
    except Exception as e:
        print(f"Invalid input: {e}")


main()


Enter a nested list (e.g., [[1,2],[3,[4,5]],6]): 2,3
Sum of all elements: 5


4.Remove Specific Element from a Nested List:

 Write a Python function that removes all occurrences of a specific element from a nested list.

 • Requirements:

 – Define a function remove
 element(lst, elem) that removes elem from lst and returns the
 modified list.

 – Example: Fortheinput lst = [[1, 2], [3, 2], [4, 5]]andelem = 2,theoutputshould
 be [[1], [3], [4, 5]].

In [ ]:
def remove_element(lst: list, elem: int) -> list:
    result = []
    for item in lst:
        if isinstance(item, list):
            result.append(remove_element(item, elem))  # Recursively process nested lists
        elif item != elem:
            result.append(item)  # Add non-matching elements
    return result

def main():
    try:
        nested_list = eval(input("Enter a nested list (e.g., [[1,2],[3,2],[4,5]]): "))
        elem = int(input("Enter the element to remove: "))
        print(f"Modified List: {remove_element(nested_list, elem)}")
    except Exception as e:
        print(f"Invalid input: {e}")

main()


Enter a nested list (e.g., [[1,2],[3,2],[4,5]]):  [[1,2,3],[4,5,6],[7,8,9]]
Enter the element to remove: 2
Modified List: [[1, 3], [4, 5, 6], [7, 8, 9]]


 5. Find the Maximum Element in a Nested List:

 Write a Python function that finds the maximum element in a nested list (regardless of depth).

 • Requirements:

 – Define a function find
 element.
 max(lst) that takes a nested list lst and returns the maximum
 – Example: For the input [[1, 2], [3, [4, 5]], 6], the output should be 6.

In [ ]:
def find_max_element(lst: list) -> int:
    max_value = float('-inf')
    for item in lst:
        if isinstance(item, list):
            max_value = max(max_value, find_max_element(item))  # Recursively find max in nested lists
        else:
            max_value = max(max_value, item)  # Compare numbers directly
    return max_value

def main():
    try:
        nested_list = eval(input("Enter a nested list (e.g., [[1,2],[3,[4,5]],6]): "))
        print(f"Maximum Element: {find_max_element(nested_list)}")
    except Exception as e:
        print(f"Invalid input: {e}")


main()


Enter a nested list (e.g., [[1,2],[3,[4,5]],6]):  [[1,2,3],[4,5,6],[7,8,9]]
Maximum Element: 9


 6. Count Occurrences of an Element in a Nested List:

 Write a Python function that counts how many times a specific element appears in a nested list.

 • Requirements:

 – Define a function count
occurrences(lst, elem) that counts the occurrences of elem in
 the nested list lst.– Example: Fortheinput lst = [[1, 2], [2, 3], [2, 4]]andelem = 2,theoutputshould
 be 3.

In [ ]:
def count_occurrences(lst: list, elem: int) -> int:

    count = 0
    for item in lst:
        if isinstance(item, list):
            count += count_occurrences(item, elem)  # Recursively count occurrences in nested lists
        elif item == elem:
            count += 1  # Increment count if element matches
    return count

def main():
    try:
        nested_list = eval(input("Enter a nested list (e.g., [[1,2],[2,3],[2,4]]): "))
        elem = int(input("Enter the element to count: "))
        print(f"Occurrences of {elem}: {count_occurrences(nested_list, elem)}")
    except Exception as e:
        print(f"Invalid input: {e}")


main()


Enter a nested list (e.g., [[1,2],[2,3],[2,4]]):  [[1,2,3],[4,5,6],[7,8,9]]
Enter the element to count: 2
Occurrences of 2: 1


 7. Flatten a List of Lists of Lists:
 Write a Python function that flattens a list of lists of lists into a single list, regardless of the depth.

 • Requirements:

 – Define a function deep
 flatten(lst) that takes a deeply nested list lst and returns a single
 flattened list.

 – Example: For the input [[[1, 2], [3, 4]], [[5, 6], [7, 8]]], the output should be
 [1, 2, 3, 4, 5, 6, 7, 8].

In [ ]:
def deep_flatten(lst: list) -> list:
    result = []
    for item in lst:
        if isinstance(item, list):
            result.extend(deep_flatten(item))  # Recursively flatten nested lists
        else:
            result.append(item)  # Add non-list elements directly
    return result

def main():
    try:
        nested_list = eval(input("Enter a deeply nested list (e.g., [[[1,2],[3,4]],[[5,6],[7,8]]]): "))
        print(f"Flattened List: {deep_flatten(nested_list)}")
    except Exception as e:
        print(f"Invalid input: {e}")


main()


Enter a deeply nested list (e.g., [[[1,2],[3,4]],[[5,6],[7,8]]]): [[[1,2],[3,4]],[[5,6],[7,8]]]
Flattened List: [1, 2, 3, 4, 5, 6, 7, 8]


 8. Nested List Average:
 Write a Python function that calculates the average of all elements in a nested list.

 • Requirements:

 – Define a function average
 of all the elements.
 nested(lst) that takes a nested list lst and returns the average

 – Example: For the input [[1, 2], [3, 4], [5, 6]], the output should be

In [ ]:
def nested_average(lst: list) -> float:
    def flatten(lst):
        result = []
        for item in lst:
            if isinstance(item, list):
                result.extend(flatten(item))  # Recursively flatten nested lists
            else:
                result.append(item)  # Add non-list elements directly
        return result

    flat_list = flatten(lst)  # Flatten the list first
    return sum(flat_list) / len(flat_list) if flat_list else 0

def main():
    try:
        nested_list = eval(input("Enter a deeply nested list (e.g., [[[1,2],[3,4]],[[5,6],[7,8]]]): "))
        print(f"Average of Elements: {nested_average(nested_list)}")
    except Exception as e:
        print(f"Invalid input: {e}")


main()


Enter a deeply nested list (e.g., [[[1,2],[3,4]],[[5,6],[7,8]]]): [[[1,2],[3,4]],[[5,6],[7,8]]]
Average of Elements: 4.5


**NumPy**

Basic Vector and Matrix Operation with Numpy.
Problem - 1: Array Creation:
Complete the following Tasks:
1. Initialize an empty array with size 2X2.
2. Initialize an all one array with size 4X2.
3. Return a new array of given shape and type, filled with fill value.{Hint: np.full}
4. Return a new array of zeros with same shape and type as a given array.{Hint: np.zeros like}
5. Return a new array of ones with same shape and type as a given array.{Hint: np.ones like}
6. For an existing list new_list = [1,2,3,4] convert to an numpy array.{Hint: np.array()}

In [ ]:
import numpy as np

In [ ]:
empty_array = np.empty((2, 2))
print("Empty Array:")
print(empty_array)

Empty Array:
[[3.00144361e-316 0.00000000e+000]
 [6.77286165e-310 2.59758539e+049]]


In [ ]:
ones_array = np.ones((4, 2))
print("All-One Array:")
print(ones_array)


All-One Array:
[[1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]]


In [ ]:
filled_array = np.full((3, 3), 7)
print("Filled Array with 7s:")
print(filled_array)

Filled Array with 7s:
[[7 7 7]
 [7 7 7]
 [7 7 7]]


In [ ]:
arr = np.array([[1, 2], [3, 4]])
zeros_array = np.zeros_like(arr)
print("Zeros Array :")
print(zeros_array)

Zeros Array :
[[0 0]
 [0 0]]


In [ ]:
ones_like_array = np.ones_like(arr)
print("Ones Array :")
print(ones_like_array)

Ones Array :
[[1 1]
 [1 1]]


In [ ]:
new_list = [1, 2, 3, 4]
numpy_array = np.array(new_list)
print("Converted NumPy Array from List:")
print(numpy_array)

Converted NumPy Array from List:
[1 2 3 4]


1. Create an array with values ranging from 10 to 49. {Hint:np.arrange()}.
2. Create a 3X3 matrix with values ranging from 0 to 8.
{Hint:look for np.reshape()}
3. Create a 3X3 identity matrix.{Hint:np.eye()}
4. Create a random array of size 30 and find the mean of the array.
{Hint:check for np.random.random() and array.mean() function}
5. Create a 10X10 array with random values and find the minimum and maximum values.
6. Create a zero array of size 10 and replace 5th element with 1.
7. Reverse an array arr = [1,2,0,0,4,0].
8. Create a 2d array with 1 on border and 0 inside.
9. Create a 8X8 matrix and fill it with a checkerboard pattern.

In [ ]:
range_array = np.arange(10, 50)
print("Array with values from 10 to 49:")
print(range_array)

Array with values from 10 to 49:
[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


In [ ]:
reshaped_matrix = np.arange(9).reshape(3, 3)
print("3x3 Matrix with values from 0 to 8:")
print(reshaped_matrix)

3x3 Matrix with values from 0 to 8:
[[0 1 2]
 [3 4 5]
 [6 7 8]]


In [ ]:
identity_matrix = np.eye(3)
print("3x3 Identity Matrix:")
print(identity_matrix)

3x3 Identity Matrix:
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [ ]:
random_array = np.random.random(30)
mean_value = random_array.mean()
print("Random Array of size 30:")
print(random_array)
print("Mean Value:", mean_value)

Random Array of size 30:
[0.73278454 0.48864513 0.96251309 0.28596112 0.68786274 0.67187462
 0.724362   0.38849603 0.42062842 0.17660536 0.19171075 0.99747513
 0.12631678 0.80600845 0.31295485 0.74859084 0.14987594 0.13019357
 0.02332528 0.34616327 0.20355537 0.76822659 0.27970106 0.41097316
 0.20151274 0.40876668 0.80585541 0.12618314 0.03074127 0.32122012]
Mean Value: 0.4309694482941343


In [ ]:
random_matrix = np.random.random((10, 10))
min_value = random_matrix.min()
max_value = random_matrix.max()
print("Random Matrix:")
print(random_matrix)
print("Minimum Value:", min_value)
print("Maximum Value:", max_value)

Random Matrix:
[[0.36564255 0.14295041 0.85570796 0.83236285 0.55473661 0.12753395
  0.30876256 0.21298148 0.02108619 0.77389446]
 [0.86007332 0.5162     0.03754273 0.3596491  0.98390405 0.66248709
  0.81680791 0.08375276 0.15252054 0.16048543]
 [0.83233924 0.45120339 0.2027618  0.97304565 0.02778625 0.88130102
  0.2469904  0.42759804 0.4848959  0.86673565]
 [0.65969349 0.84020852 0.05728908 0.54393198 0.47937267 0.58398046
  0.31639815 0.8890703  0.54045236 0.18563241]
 [0.68241025 0.72265846 0.66387292 0.80568738 0.50707019 0.8426558
  0.80601099 0.47603625 0.72882129 0.25996262]
 [0.54416343 0.43146756 0.62112812 0.86259258 0.2633718  0.81920892
  0.68872869 0.33541898 0.06613625 0.35381327]
 [0.13285415 0.78910186 0.06615917 0.96691384 0.17385594 0.46734916
  0.72693047 0.72371145 0.05414912 0.56358487]
 [0.17997273 0.56499455 0.96005544 0.74471289 0.94514529 0.05549338
  0.20212273 0.17812144 0.93869555 0.14680147]
 [0.78294578 0.58298399 0.18377146 0.44658481 0.35880629 0.4362854

In [ ]:
zero_array = np.zeros(10)
zero_array[4] = 1
print("Zero Array with 5th Element as 1:")
print(zero_array)

Zero Array with 5th Element as 1:
[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]


In [ ]:
arr = np.array([1, 2, 0, 0, 4, 0])
reversed_array = arr[::-1]
print("Reversed Array:")
print(reversed_array)

Reversed Array:
[0 4 0 0 2 1]


In [ ]:
border_array = np.ones((5, 5))
border_array[1:-1, 1:-1] = 0
print("Array with 1 on border and 0 inside:")
print(border_array)

Array with 1 on border and 0 inside:
[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


In [ ]:
checkerboard = np.zeros((8, 8))
checkerboard[1::2, ::2] = 1
checkerboard[::2, 1::2] = 1
print("Checkerboard Pattern:")
print(checkerboard)

Checkerboard Pattern:
[[0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]]


For the following arrays:
x = np.array([[1,2],[3,5]]) and y = np.array([[5,6],[7,8]]);
v = np.array([9,10]) and w = np.array([11,12]);
Complete all the task using numpy:
1. Add the two array.
2. Subtract the two array.
3. Multiply the array with any integers of your choice.
4. Find the square of each element of the array.
5. Find the dot product between: v(and)w ; x(and)v ; x(and)y.
6. Concatenate x(and)y along row and Concatenate v(and)w along column.
{Hint:try np.concatenate() or np.vstack() functions.
7. Concatenate x(and)v; if you get an error, observe and explain why did you get the error?

In [ ]:
x = np.array([[1,2],[3,5]])
y = np.array([[5,6],[7,8]]);
v = np.array([9,10])
w = np.array([11,12]);

In [ ]:
add = x + y
print("Sum of x and y:")
print(add)

Sum of x and y:
[[ 6  8]
 [10 13]]


In [ ]:
diff = x - y
print("Difference of x and y:")
print(diff)


Difference of x and y:
[[-4 -4]
 [-4 -3]]


In [ ]:
multiplied = x * 2
print("Multiplication of x by 2:")
print(multiplied)

Multiplication of x by 2:
[[ 2  4]
 [ 6 10]]


In [ ]:
squared_x = np.square(x)
print("Square of each element in x:")
print(squared_x)

Square of each element in x:
[[ 1  4]
 [ 9 25]]


In [ ]:

dot_vw = np.dot(v, w)
dot_xv = np.dot(x, v)
dot_xy = np.dot(x, y)
print("Dot Product of v and w:", dot_vw)
print("Dot Product of x and v:", dot_xv)
print("Dot Product of x and y:")
print(dot_xy)


Dot Product of v and w: 219
Dot Product of x and v: [29 77]
Dot Product of x and y:
[[19 22]
 [50 58]]


In [ ]:

concat_xy = np.concatenate((x, y), axis=1)
concat_vw = np.vstack((v, w))
print("Concatenation of x and y along rows:")
print(concat_xy)
print("Concatenation of v and w along columns:")
print(concat_vw)

Concatenation of x and y along rows:
[[1 2 5 6]
 [3 5 7 8]]
Concatenation of v and w along columns:
[[ 9 10]
 [11 12]]


In [ ]:
concat_xv = np.concatenate((x, v), axis=1)


ValueError: all the input arrays must have same number of dimensions, but the array at index 0 has 2 dimension(s) and the array at index 1 has 1 dimension(s)

Problem - 4: Matrix Operations:
• For the following arrays:
A = np.array([[3,4],[7,8]]) and B = np.array([[5,3],[2,1]]);
Prove following with Numpy:
1. Prove A.A−1 = I.
2. Prove AB ̸= BA.
3. Prove (AB)

T = BTAT
.

• Solve the following system of Linear equation using Inverse Methods.

2x − 3y + z = −1
x − y + 2z = −3
3x + y − z = 9

{Hint: First use Numpy array to represent the equation in Matrix form. Then Solve for: AX = B}

• Now: solve the above equation using np.linalg.inv function.{Explore more about ”linalg” func-
tion of Numpy}

In [ ]:
A = np.array([[3, 4], [7, 8]])
B = np.array([[5, 3], [2, 1]])


In [ ]:
A_inv = np.linalg.inv(A)
result = np.dot(A, A_inv)
print("A.A−1 = I")
print(result)

A.A−1 = I
[[1.00000000e+00 0.00000000e+00]
 [1.77635684e-15 1.00000000e+00]]


In [ ]:
AB = np.dot(A, B)
BA = np.dot(B, A)
print("AB:",AB)
print("BA:",BA)
print("Is AB equal to BA:",  np.array_equal(AB, BA))

AB: [[23 13]
 [51 29]]
BA: [[36 44]
 [13 16]]
Is AB equal to BA: False


In [ ]:
transpose_AB = np.transpose(AB)
BTAT = np.dot(B.T, A.T)
print("AB transpose:")
print(transpose_AB)
print("B transpose * A transpose:")
print(BTAT)
print("Is AB transpose equal to (B transpose * A transpose):", np.array_equal(transpose_AB, BTAT))

AB transpose:
[[23 51]
 [13 29]]
B transpose * A transpose:
[[23 51]
 [13 29]]
Is AB transpose equal to (B transpose * A transpose): True


In [ ]:
coeff_matrix = np.array([[2, -3, 1], [1, -1, 2], [3, 1, -1]])
constants = np.array([-1, -3, 9])

In [ ]:
coeff_matrix_inv = np.linalg.inv(coeff_matrix)
solution = np.dot(coeff_matrix_inv, constants)
print("Solution using inverse method:")
print(solution)

Solution using inverse method:
[ 2.  1. -2.]


Experiment: How Fast is Numpy?
In this exercise, you will compare the performance and implementation of operations using plain Python
lists (arrays) and NumPy arrays. Follow the instructions:
1. Element-wise Addition:
• Using Python Lists, perform element-wise addition of two lists of size 1, 000, 000. Measure
and Print the time taken for this operation.
• Using Numpy Arrays, Repeat the calculation and measure and print the time taken for
this operation.
2. Element-wise Multiplication
• Using Python Lists, perform element-wise multiplication of two lists of size 1, 000, 000.
Measure and Print the time taken for this operation.
• Using Numpy Arrays, Repeat the calculation and measure and print the time taken for
this operation.
3. Dot Product
• Using Python Lists, compute the dot product of two lists of size 1, 000, 000. Measure and
Print the time taken for this operation.
• Using Numpy Arrays, Repeat the calculation and measure and print the time taken for
this operation.
4. Matrix Multiplication

• Using Python lists, perform matrix multiplication of two matrices of size 1000x1000. Mea-
sure and print the time taken for this operation.

• Using NumPy arrays, perform matrix multiplication of two matrices of size 1000x1000.
Measure and print the time taken for this operation.

In [ ]:
import time
size = 1000000

list1 = list(range(size))
list2 = list(range(size))

In [ ]:
start = time.time()
list_sum = [list1[i] + list2[i] for i in range(size)]
time_list_add = time.time() - start

array1 = np.arange(size)
array2 = np.arange(size)

start = time.time()
array_sum = array1 + array2
time_numpy_add = time.time() - start

print("Element-wise Addition:")
print("Python List Time:", time_list_add)
print("NumPy Array Time:", time_numpy_add)

Element-wise Addition:
Python List Time: 0.09306573867797852
NumPy Array Time: 0.004523515701293945


In [ ]:
start = time.time()
list_mult = [list1[i] * list2[i] for i in range(size)]
time_list_mult = time.time() - start

start = time.time()
array_mult = array1 * array2
time_numpy_mult = time.time() - start

print("Element-wise Multiplication:")
print("Python List Time:", time_list_mult)
print("NumPy Array Time:", time_numpy_mult)

Element-wise Multiplication:
Python List Time: 0.09746909141540527
NumPy Array Time: 0.005206108093261719


In [ ]:
start = time.time()
dot_list = np.sum(list1[i] * list2[i] for i in range(size))
time_list_dot = time.time() - start

start = time.time()
dot_numpy = np.dot(array1, array2)
time_numpy_dot = time.time() - start

print("Dot Product:")
print("Python List Time:", time_list_dot)
print("NumPy Array Time:", time_numpy_dot)

<ipython-input-68-5ae196f1f43b>:2: DeprecationWarning: Calling np.sum(generator) is deprecated, and in the future will give a different result. Use np.sum(np.fromiter(generator)) or the python sum builtin instead.
  dot_list = np.sum(list1[i] * list2[i] for i in range(size))


Dot Product:
Python List Time: 0.2646675109863281
NumPy Array Time: 0.008721590042114258


In [ ]:
matrix_size = 300
list_matrix1 = [[i for i in range(matrix_size)] for _ in range(matrix_size)]
list_matrix2 = [[i for i in range(matrix_size)] for _ in range(matrix_size)]

start = time.time()
result_matrix = [[np.sum(a * b for a, b in zip(row, col)) for col in zip(*list_matrix2)] for row in list_matrix1]
time_list_mat_mult = time.time() - start

numpy_matrix1 = np.arange(matrix_size**2).reshape(matrix_size, matrix_size)
numpy_matrix2 = np.arange(matrix_size**2).reshape(matrix_size, matrix_size)

start = time.time()
result_numpy_matrix = np.dot(numpy_matrix1, numpy_matrix2)
time_numpy_mat_mult = time.time() - start

print("\nMatrix Multiplication (300x300):")
print("Python List Time:", time_list_mat_mult)
print("NumPy Array Time:", time_numpy_mat_mult)

<ipython-input-74-8b92380e5d12>:6: DeprecationWarning: Calling np.sum(generator) is deprecated, and in the future will give a different result. Use np.sum(np.fromiter(generator)) or the python sum builtin instead.
  result_matrix = [[np.sum(a * b for a, b in zip(row, col)) for col in zip(*list_matrix2)] for row in list_matrix1]



Matrix Multiplication (300x300):
Python List Time: 3.189610004425049
NumPy Array Time: 0.04607105255126953
